# https://github.com/jaspervdj/stylish-haskell/blob/master/data/stylish-haskell.yaml

steps:

  - simple_align:
      cases: true
      top_level_patterns: true

  - imports:
      align: group
      list_align: after_alias
      long_list_align: inline
      list_padding: 4
      pad_module_names: true
      separate_lists: true

  - trailing_whitespace: {}

columns: 80
